export const users = [
    {
        "_id": "59232f57d97bdf1d0371e093",
        "index": 0,
        "guid": "71bf5a59-f998-4586-a36c-99395677703e",
        "isActive": false,
        "balance": "$3,903.88",
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "eyeColor": "brown",
        "name": "Olsen Jennings",
        "gender": "male",
        "company": "SIGNITY",
        "email": "olsenjennings@signity.com",
        "phone": "+1 (979) 403-3136",
        "address": "472 Myrtle Avenue, Beechmont, Indiana, 5944",
        "about": "Dolor ipsum pariatur nostrud sit. Et pariatur nisi nulla excepteur et fugiat est amet commodo enim. Id elit cupidatat incididunt irure deserunt.\r\n",
        "registered": "2015-05-21T03:09:21 -02:00",
        "latitude": 45.412088,
        "longitude": -67.24916,
        "tags": [
            "consequat",
            "aliqua",
            "Lorem",
            "elit",
            "consequat",
            "cupidatat",
            "consectetur"
        ],
        "favoriteFruit": "banana"
    },
    {
        "_id": "59232f57400a27655f667008",
        "index": 1,
        "guid": "6b94193c-88f8-4a56-a93e-83706d2d079c",
        "isActive": false,
        "balance": "$2,925.76",
        "picture": "http://placehold.it/32x32",
        "age": 36,
        "eyeColor": "green",
        "name": "Laurie Haney",
        "gender": "female",
        "company": "ENOMEN",
        "email": "lauriehaney@enomen.com",
        "phone": "+1 (988) 515-3938",
        "address": "362 Dover Street, Floriston, Alaska, 3964",
        "about": "Aliquip non adipisicing ea et aliqua tempor eiusmod enim excepteur ut sint commodo ullamco. Cupidatat cillum voluptate quis sint excepteur adipisicing consequat consequat id ipsum aliqua. Velit excepteur sit sunt nisi exercitation nisi do laboris non ullamco dolore ut exercitation. Amet exercitation dolore quis aute amet nulla. In fugiat cupidatat laboris elit adipisicing non officia duis magna et.\r\n",
        "registered": "2016-07-07T12:14:02 -02:00",
        "latitude": -35.881284,
        "longitude": -138.960848,
        "tags": [
            "ex",
            "id",
            "consectetur",
            "ad",
            "in",
            "id",
            "ullamco"
        ],
        "favoriteFruit": "apple"
    },
    {
        "_id": "59232f57d3b8696620494f58",
        "index": 2,
        "guid": "cd2132e2-fbf7-4b12-8fef-4210d4af0417",
        "isActive": false,
        "balance": "$3,311.66",
        "picture": "http://placehold.it/32x32",
        "age": 20,
        "eyeColor": "brown",
        "name": "Catalina Payne",
        "gender": "female",
        "company": "BOILICON",
        "email": "catalinapayne@boilicon.com",
        "phone": "+1 (924) 543-3207",
        "address": "785 Thomas Street, Bladensburg, Puerto Rico, 6649",
        "about": "Ullamco non nisi ullamco qui do sunt anim. Irure sunt veniam eiusmod consequat dolore velit cillum laborum fugiat Lorem laborum eu. Sunt irure minim in laborum aute velit ullamco aute magna consequat amet quis elit cupidatat. Sint eu ut reprehenderit excepteur. Pariatur ex exercitation ea aliqua nostrud eiusmod qui cillum sunt dolore. Incididunt duis proident ipsum tempor qui do officia reprehenderit cupidatat velit. Consectetur non tempor sint quis amet.\r\n",
        "registered": "2016-05-03T02:19:56 -02:00",
        "latitude": -27.698001,
        "longitude": 89.110379,
        "tags": [
            "cupidatat",
            "cillum",
            "cupidatat",
            "elit",
            "pariatur",
            "amet",
            "irure"
        ],
        "favoriteFruit": "strawberry"
    },
    {
        "_id": "59232f570eac252093af341d",
        "index": 3,
        "guid": "2502d5b3-b787-4323-bcb3-115e6a5cc080",
        "isActive": false,
        "balance": "$3,733.59",
        "picture": "http://placehold.it/32x32",
        "age": 34,
        "eyeColor": "green",
        "name": "Fitzgerald Duke",
        "gender": "male",
        "company": "HARMONEY",
        "email": "fitzgeraldduke@harmoney.com",
        "phone": "+1 (837) 499-3140",
        "address": "297 Woodside Avenue, Marbury, Oklahoma, 381",
        "about": "Velit in Lorem esse esse ex laborum ullamco laborum. Velit fugiat cillum nostrud aliqua cillum aliqua. Labore mollit labore occaecat velit est qui Lorem officia deserunt.\r\n",
        "registered": "2015-09-22T10:08:53 -02:00",
        "latitude": -69.967779,
        "longitude": 63.192274,
        "tags": [
            "id",
            "sunt",
            "aliquip",
            "qui",
            "laborum",
            "voluptate",
            "qui"
        ],
        "favoriteFruit": "banana"
    },
    {
        "_id": "59232f57d82a68caafa06315",
        "index": 4,
        "guid": "06a44fe8-a1dc-4c86-a70a-fb45a7d1ae5e",
        "isActive": false,
        "balance": "$2,417.32",
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "eyeColor": "green",
        "name": "Fuller Cherry",
        "gender": "male",
        "company": "ZOSIS",
        "email": "fullercherry@zosis.com",
        "phone": "+1 (995) 455-2628",
        "address": "447 Langham Street, Fontanelle, Marshall Islands, 7098",
        "about": "Anim sunt nulla anim exercitation. Consequat cupidatat duis qui fugiat dolore in adipisicing. In proident proident Lorem ipsum dolore cillum laboris in amet duis cillum sit velit incididunt. Ad in ad pariatur cupidatat.\r\n",
        "registered": "2014-10-16T12:33:18 -02:00",
        "latitude": -23.304102,
        "longitude": 56.458674,
        "tags": [
            "anim",
            "reprehenderit",
            "aute",
            "occaecat",
            "labore",
            "minim",
            "veniam"
        ],
        "favoriteFruit": "apple"
    }
];

