exports.ids = [0];
exports.modules = {

/***/ 489:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(9);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__app_lazy_lazy_module__ = __webpack_require__(490);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_router__ = __webpack_require__(79);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "LazyModuleNgFactory", function() { return LazyModuleNgFactory; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RenderType_LazyView", function() { return RenderType_LazyView; });
/* harmony export (immutable) */ __webpack_exports__["View_LazyView_0"] = View_LazyView_0;
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "LazyViewNgFactory", function() { return LazyViewNgFactory; });
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();



var LazyModuleInjector = (function (_super) {
    __extends(LazyModuleInjector, _super);
    function LazyModuleInjector(parent) {
        return _super.call(this, parent, [LazyViewNgFactory], []) || this;
    }
    LazyModuleInjector.prototype.createInternal = function () {
        this._RouterModule_0 = new __WEBPACK_IMPORTED_MODULE_2__angular_router__["q" /* RouterModule */](this.parent.get(__WEBPACK_IMPORTED_MODULE_2__angular_router__["r" /* ɵa */], null), this.parent.get(__WEBPACK_IMPORTED_MODULE_2__angular_router__["j" /* Router */], null));
        this._LazyModule_1 = new __WEBPACK_IMPORTED_MODULE_1__app_lazy_lazy_module__["a" /* LazyModule */]();
        this._ROUTES_2 = [[{
                    path: '',
                    component: __WEBPACK_IMPORTED_MODULE_1__app_lazy_lazy_module__["b" /* LazyView */],
                    pathMatch: 'full'
                }
            ]];
        return this._LazyModule_1;
    };
    LazyModuleInjector.prototype.getInternal = function (token, notFoundResult) {
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_router__["q" /* RouterModule */])) {
            return this._RouterModule_0;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_1__app_lazy_lazy_module__["a" /* LazyModule */])) {
            return this._LazyModule_1;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_router__["u" /* ROUTES */])) {
            return this._ROUTES_2;
        }
        return notFoundResult;
    };
    LazyModuleInjector.prototype.destroyInternal = function () {
    };
    return LazyModuleInjector;
}(__WEBPACK_IMPORTED_MODULE_0__angular_core__["A" /* ɵNgModuleInjector */]));
var LazyModuleNgFactory = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["B" /* NgModuleFactory */](LazyModuleInjector, __WEBPACK_IMPORTED_MODULE_1__app_lazy_lazy_module__["a" /* LazyModule */]);
var styles_LazyView = [];
var RenderType_LazyView = __WEBPACK_IMPORTED_MODULE_0__angular_core__["C" /* ɵcrt */]({
    encapsulation: 2,
    styles: styles_LazyView,
    data: {}
});
function View_LazyView_0(l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["D" /* ɵvid */](0, [
        (l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["E" /* ɵeld */](0, null, null, 1, 'h3', [], null, null, null, null, null)),
        (l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["F" /* ɵted */](null, ['i\'m lazy']))
    ], null, null);
}
function View_LazyView_Host_0(l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["D" /* ɵvid */](0, [
        (l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["E" /* ɵeld */](0, null, null, 1, 'lazy-view', [], null, null, null, View_LazyView_0, RenderType_LazyView)),
        __WEBPACK_IMPORTED_MODULE_0__angular_core__["G" /* ɵdid */](24576, null, 0, __WEBPACK_IMPORTED_MODULE_1__app_lazy_lazy_module__["b" /* LazyView */], [], null, null)
    ], null, null);
}
var LazyViewNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["H" /* ɵccf */]('lazy-view', __WEBPACK_IMPORTED_MODULE_1__app_lazy_lazy_module__["b" /* LazyView */], View_LazyView_Host_0, {}, {}, []);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxyaWsuT2xzb24vRG9jdW1lbnRzL1NvdXJjZS9NaXNjL1BsYXlncm91bmQvZHMtaW50ZXJuYWwtdG9vbHMvc3JjL2FwcC8rbGF6eS9sYXp5Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9BbHJpay5PbHNvbi9Eb2N1bWVudHMvU291cmNlL01pc2MvUGxheWdyb3VuZC9kcy1pbnRlcm5hbC10b29scy9zcmMvYXBwLytsYXp5L2xhenkubW9kdWxlLnRzIiwibmc6Ly8vQzovVXNlcnMvQWxyaWsuT2xzb24vRG9jdW1lbnRzL1NvdXJjZS9NaXNjL1BsYXlncm91bmQvZHMtaW50ZXJuYWwtdG9vbHMvc3JjL2FwcC8rbGF6eS9sYXp5Lm1vZHVsZS50cy5MYXp5Vmlldy5odG1sIiwibmc6Ly8vQzovVXNlcnMvQWxyaWsuT2xzb24vRG9jdW1lbnRzL1NvdXJjZS9NaXNjL1BsYXlncm91bmQvZHMtaW50ZXJuYWwtdG9vbHMvc3JjL2FwcC8rbGF6eS9sYXp5Lm1vZHVsZS50cy5MYXp5Vmlld19Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMz5pJ20gbGF6eTwvaDM+IiwiPGxhenktdmlldz48L2xhenktdmlldz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJOzs7Ozs7SUNBSjtnQkFBQTs7OzsifQ==
//# sourceMappingURL=lazy.module.ngfactory.js.map

/***/ }),

/***/ 490:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "b", function() { return LazyView; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return LazyModule; });
var LazyView = (function () {
    function LazyView() {
    }
    return LazyView;
}());

var LazyModule = (function () {
    function LazyModule() {
    }
    return LazyModule;
}());

//# sourceMappingURL=lazy.module.js.map

/***/ })

};;
//# sourceMappingURL=0.server.js.map